# Generated by Django 5.2.17 on 2026-09-24 18:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique code identifying the course (e.g. BTECH_CSE, MBA_FIN).', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Full academic title of the program.', max_length=200)),
                ('degree_level', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate (UG)'), ('POSTGRADUATE', 'Postgraduate (PG)'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('DOCTORAL', 'Doctoral (Ph.D.)')], db_index=True, default='UNDERGRADUATE', max_length=30)),
                ('department', models.CharField(blank=True, help_text='Academic department or faculty.', max_length=100)),
                ('duration_years', models.DecimalField(decimal_places=1, default=Decimal('4.0'), help_text='Duration of the program in years.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('fee_per_year', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual tuition fee in local currency.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls visibility in lead assignment and intake forms.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['degree_level', 'is_active'], name='idx_course_level_active')],
            },
        ),
    ]
