# Generated by Django 5.2.17 on 2026-09-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_assigned_counsellor', models.ForeignKey(blank=True, help_text='Last counsellor to receive an automated lead assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment State',
                'verbose_name_plural': 'Assignment State',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_number', models.CharField(db_index=True, editable=False, help_text='System-generated unique identifier (e.g. LED-YYYYMM-XXXXX).', max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=25)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website Enquiry'), ('WALK_IN', 'Walk-In / Campus Visit'), ('PHONE', 'Phone Call'), ('WHATSAPP', 'WhatsApp'), ('EDUCATION_FAIR', 'Education Fair / Expo'), ('CAMPAIGN', 'Digital Campaign (Ads)'), ('REFERRAL', 'Student / Alumni Referral'), ('OTHER', 'Other Source')], db_index=True, default='WEBSITE', max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('COUNSELLING_SCHEDULED', 'Counselling Scheduled'), ('APPLICATION_STARTED', 'Application Started'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('CONVERTED', 'Converted'), ('NO_RESPONSE', 'No Response'), ('NOT_INTERESTED', 'Not Interested'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=30)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], db_index=True, default='MEDIUM', help_text='Operational priority for outreach.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='General counsellor remarks and background context.')),
                ('loss_reason', models.CharField(blank=True, choices=[('FEES_HIGH', 'Tuition / Fee Constraint'), ('DISTANCE_LOCATION', 'Distance / Relocation Constraint'), ('CHOSE_COMPETITOR', 'Admitted to Another Institution'), ('INELIGIBLE_ACADEMICS', 'Academic Ineligibility / Minimum Marks'), ('COURSE_NOT_OFFERED', 'Desired Specialization Not Offered'), ('UNRESPONSIVE_EXHAUSTED', 'Unresponsive After Maximum Attempts'), ('OTHER', 'Other / Personal Reason')], help_text='Mandatory reason if status is LOST or NOT_INTERESTED.', max_length=50, null=True)),
                ('loss_notes', models.TextField(blank=True, help_text='Additional context on loss or rejection.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag preserving historical records.')),
                ('counsellor', models.ForeignKey(blank=True, help_text='Assigned admission counsellor.', limit_choices_to={'role': 'COUNSELLOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, help_text='Primary academic program preference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.course')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='Scheduled date and time for the follow-up.')),
                ('followup_type', models.CharField(choices=[('PHONE_CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp Message'), ('EMAIL', 'Email'), ('IN_PERSON_MEETING', 'In-Person Meeting'), ('CAMPUS_TOUR', 'Campus Tour / Visit')], default='PHONE_CALL', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Scheduled / Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('CONNECTED_POSITIVE', 'Connected - Positive Interest'), ('CONNECTED_BUSY_CALL_BACK', 'Connected - Requested Callback'), ('RINGING_NO_ANSWER', 'Ringing - No Answer'), ('NUMBER_INVALID', 'Invalid / Unreachable Number'), ('WHATSAPP_SENT', 'WhatsApp Info Sent'), ('EMAIL_SENT', 'Email Prospectus Sent'), ('MEETING_COMPLETED', 'Counselling Session Completed'), ('MEETING_NO_SHOW', 'Candidate Missed Session (No-Show)')], help_text='Recorded result once follow-up is completed.', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Interaction summary notes.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Counsellor responsible for conducting the interaction.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(help_text='Associated lead.', on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('COUNSELLOR_CHANGED', 'Counsellor Reassigned'), ('STATUS_CHANGED', 'Status Changed'), ('FOLLOWUP_CREATED', 'Follow-up Scheduled'), ('FOLLOWUP_COMPLETED', 'Follow-up Completed'), ('COURSE_CHANGED', 'Course Preference Changed'), ('LEAD_UPDATED', 'Lead Details Updated'), ('NOTE_ADDED', 'Counsellor Note Added')], db_index=True, max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True, help_text='Human-readable summary or remarks.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Staff member who performed this action (null if automated system action).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'counsellor'], name='idx_lead_status_counsellor'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='idx_lead_status_created'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone', 'email'], name='idx_lead_phone_email'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'status'], name='idx_lead_source_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_followup_at', 'status'], name='idx_lead_next_followup'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status', 'scheduled_at'], name='idx_followup_status_sched'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['lead', 'status'], name='idx_followup_lead_status'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to', 'status', 'scheduled_at'], name='idx_followup_user_sched'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['lead', 'created_at'], name='idx_actlog_lead_created'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type', 'created_at'], name='idx_actlog_type_created'),
        ),
    ]
