# Generated by Django 5.2.17 on 2026-09-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('COUNSELLOR_CHANGED', 'Counsellor Reassigned'), ('STATUS_CHANGED', 'Status Changed'), ('FOLLOWUP_CREATED', 'Follow-up Scheduled'), ('FOLLOWUP_COMPLETED', 'Follow-up Completed'), ('FOLLOWUP_MISSED', 'Follow-up Marked Missed'), ('FOLLOWUP_CANCELLED', 'Follow-up Cancelled'), ('COURSE_CHANGED', 'Course Preference Changed'), ('LEAD_UPDATED', 'Lead Details Updated'), ('NOTE_ADDED', 'Counsellor Note Added')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='followup',
            name='followup_type',
            field=models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('COUNSELLING', 'Counselling Session'), ('MEETING', 'In-Person Meeting'), ('PHONE_CALL', 'Phone Call (Legacy)'), ('CAMPUS_TOUR', 'Campus Tour (Legacy)')], default='CALL', max_length=30),
        ),
        migrations.AlterField(
            model_name='followup',
            name='outcome',
            field=models.CharField(blank=True, choices=[('CONNECTED_POSITIVE', 'Connected - Positive Interest'), ('CONNECTED_BUSY_CALL_BACK', 'Connected - Requested Callback'), ('RINGING_NO_ANSWER', 'Ringing - No Answer'), ('NUMBER_INVALID', 'Invalid / Unreachable Number'), ('WHATSAPP_SENT', 'WhatsApp Info Sent'), ('EMAIL_SENT', 'Email Prospectus Sent'), ('MEETING_COMPLETED', 'Session / Meeting Completed'), ('MEETING_NO_SHOW', 'Candidate Missed Session (No-Show)')], help_text='Recorded result once follow-up is completed.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
