# Generated by Django 5.2.17 on 2026-09-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_activitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
